// <auto-generated />
using System;
using Domashna.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domashna.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domashna.Data.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Popularity")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Name = "Steven Spielberg",
                            Popularity = true
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Name = "Martin Scorsese",
                            Popularity = false
                        },
                        new
                        {
                            Id = 3,
                            Country = "England",
                            Name = "Alfred Hitchcock ",
                            Popularity = true
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            Name = "Stanley Kubrick",
                            Popularity = false
                        },
                        new
                        {
                            Id = 5,
                            Country = "USA",
                            Name = "Quentin Tarantino",
                            Popularity = false
                        },
                        new
                        {
                            Id = 6,
                            Country = "Yugoslavia",
                            Name = "Krsto Papic",
                            Popularity = true
                        },
                        new
                        {
                            Id = 7,
                            Country = "USA",
                            Name = "Orson Welles",
                            Popularity = true
                        },
                        new
                        {
                            Id = 8,
                            Country = "USA",
                            Name = "Francis Ford Coppola",
                            Popularity = false
                        },
                        new
                        {
                            Id = 9,
                            Country = "England",
                            Name = "Ridley Scott",
                            Popularity = true
                        },
                        new
                        {
                            Id = 10,
                            Country = "Japan",
                            Name = "Akira Kurosawa",
                            Popularity = false
                        });
                });

            modelBuilder.Entity("Domashna.Data.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Thrillers"
                        },
                        new
                        {
                            Id = 8,
                            Name = "General"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sci-fi"
                        });
                });

            modelBuilder.Entity("Domashna.Data.Entities.ListingMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ListingMovies");
                });

            modelBuilder.Entity("Domashna.Data.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectorID")
                        .HasColumnType("int");

                    b.Property<string>("DirectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IMBDScore")
                        .HasColumnType("float");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SoldItems")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YearOfRelease")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DirectorID");

                    b.HasIndex("GenreID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Description = "Jurassic Park is a 1993 American science fiction adventure film directed by Steven Spielberg and produced by Kathleen Kennedy and Gerald R.Molen. It is the first installment in the Jurassic Park franchise, and is based on the 1990 novel of the same name by Michael Crichton and a screenplay written byCrichton and David Koepp. The film is set on the fictional island of Isla Nublar, located off Central America's Pacific Coast near Costa Rica.There, wealthy businessman John Hammond and a team of genetic scientists have created a wildlife park of de-extinct dinosaurs.When industrial sabotage leads to a catastrophic shutdown of the park's power facilities and security precautions, a small group of visitors andHammond's grandchildren struggle to survive and escape the perilous island.",
                            DirectorID = 1,
                            DirectorName = "Steven Spielberg",
                            GenreID = 6,
                            GenreName = "Fantasy",
                            IMBDScore = 8.0999999999999996,
                            Language = "English",
                            PhotoURL = "Jurassic_Park_poster.jpg",
                            Price = 9.9900000000000002,
                            SoldItems = 0,
                            Title = "Jurassic Park",
                            UserId = 0,
                            YearOfRelease = new DateTime(1993, 6, 9, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Description = "Opening with the Allied invasion of Normandy on 6 June 1944, members of the 2nd Ranger Battalion under Cpt.Miller fight ashore to secure a beachhead. Amidst the fighting, two brothers are killed in action. Earlier in New Guinea, a third brother is KIA.Their mother, Mrs. Ryan, is to receive all three of the grave telegrams on the same day. The United States Army Chief of Staff, George C. Marshall,is given an opportunity to alleviate some of her grief when he learns of a fourth brother, Private James Ryan, and decides to send out 8 men(Cpt. Miller and select members from 2nd Rangers) to find him and bring him back home to his mother... Written by J.Zelman",
                            DirectorID = 1,
                            DirectorName = "Steven Spielberg",
                            GenreID = 2,
                            GenreName = "Action",
                            IMBDScore = 8.0999999999999996,
                            Language = "English",
                            PhotoURL = "Saving_Private_Ryan_poster.jpg",
                            Price = 14.99,
                            SoldItems = 0,
                            Title = "Saving Private Ryan",
                            UserId = 0,
                            YearOfRelease = new DateTime(1981, 7, 24, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Country = "USA",
                            Description = "A young family are visited by ghosts in their home. At first the ghosts appear friendly, moving objects around the house to the amusement of everyone,then they turn nasty and start to terrorise the family before they kidnap the youngest daughter. Written by Rob Hartill",
                            DirectorID = 1,
                            DirectorName = "Steven Spielberg",
                            GenreID = 9,
                            GenreName = "Horror",
                            IMBDScore = 7.2999999999999998,
                            Language = "English",
                            PhotoURL = "Poltergeist_(1982).png",
                            Price = 14.99,
                            SoldItems = 0,
                            Title = "Poltergeist",
                            UserId = 0,
                            YearOfRelease = new DateTime(1982, 6, 4, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            Description = "JHenry Hill might be a small time gangster, who may have taken part in a robbery with Jimmy Conway and Tommy De Vito,two other gangsters who might have set their sights a bit higher. His two partners could kill off everyone else involved in the robbery,and slowly start to think about climbing up through the hierarchy of the Mob. Henry, however, might be badly affected by his partners' success,but will he consider stooping low enough to bring about the downfall of Jimmy and Tommy? Written by Colin Tinto",
                            DirectorID = 2,
                            DirectorName = "Martin Scorsese",
                            GenreID = 3,
                            GenreName = "Crime",
                            IMBDScore = 8.6999999999999993,
                            Language = "English",
                            PhotoURL = "Goodfellas.jpg",
                            Price = 9.9900000000000002,
                            SoldItems = 0,
                            Title = "Goodfellas",
                            UserId = 0,
                            YearOfRelease = new DateTime(1990, 5, 21, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Country = "USA",
                            Description = "Phoenix office worker Marion Crane is fed up with the way life has treated her. She has to meet her lover Sam in lunch breaks,and they cannot get married because Sam has to give most of his money away in alimony. One Friday, Marion is trusted to bank forty thousand dollars by her employer.Seeing the opportunity to take the money and start a new life, Marion leaves town and heads towards Sam's California store.Tired after the long drive and caught in a storm, she gets off the main highway and pulls into the Bates Motel.The motel is managed by a quiet young man called Norman who seems to be dominated by his mother. Written by Col Needham",
                            DirectorID = 3,
                            DirectorName = "Alfred Hitchcock",
                            GenreID = 7,
                            GenreName = "Thriller",
                            IMBDScore = 8.5,
                            Language = "English",
                            PhotoURL = "Psycho_(1960)_theatrical_poster.jpg",
                            Price = 4.9900000000000002,
                            SoldItems = 0,
                            Title = "Psycho",
                            UserId = 0,
                            YearOfRelease = new DateTime(1960, 9, 8, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Country = "USA",
                            Description = "2001 is a story of evolution. Sometime in the distant past, someone or something nudged evolution by placing a monolith on Earth (presumably elsewhere throughout the universe as well). Evolution then enabled humankind to reach the moon's surface, where yet another monolith is found,one that signals the monolith placers that humankind has evolved that far. Now a race begins between computers (HAL) and human (Bowman) to reach the monolith placers.The winner will achieve the next step in evolution, whatever that may be. Written by Larry Cousins",
                            DirectorID = 4,
                            DirectorName = "Stanley Kubrick",
                            GenreID = 10,
                            GenreName = "Sci-fi",
                            IMBDScore = 8.3000000000000007,
                            Language = "English",
                            PhotoURL = "2001_A_Space_Odyssey_(1968).png",
                            Price = 9.9900000000000002,
                            SoldItems = 0,
                            Title = "2001: A Space Odyssey",
                            UserId = 0,
                            YearOfRelease = new DateTime(1968, 5, 12, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Country = "USA",
                            Description = "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer,mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town.Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of aseries of funny, bizarre and uncalled-for incidents. Written by Soumitra",
                            DirectorID = 5,
                            DirectorName = "Quentin Tarantino",
                            GenreID = 3,
                            GenreName = "Crime",
                            IMBDScore = 8.9000000000000004,
                            Language = "English",
                            PhotoURL = "Pulp_Fiction_(1994)_poster.jpg",
                            Price = 19.989999999999998,
                            SoldItems = 0,
                            Title = "Pulp Fiction",
                            UserId = 0,
                            YearOfRelease = new DateTime(1994, 10, 14, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Country = "Yugoslavia",
                            Description = "Life and times of Nikola Tesla, famous scientist whose inventions were stolen,but whose greatest contribution to mankind remain a mystery to this day. Written by Dragan Antulov",
                            DirectorID = 6,
                            DirectorName = "Krsto Papic",
                            GenreID = 5,
                            GenreName = "Drama",
                            IMBDScore = 7.4000000000000004,
                            Language = "English",
                            PhotoURL = "AL.jpg",
                            Price = 9.9900000000000002,
                            SoldItems = 0,
                            Title = "The Secret Life of Nikola Tesla",
                            UserId = 0,
                            YearOfRelease = new DateTime(1980, 2, 19, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Country = "Japan",
                            Description = "When a powerful warlord in medieval Japan dies, a poor thief recruited to impersonate him finds difficulty living up to his role and clashes with the spirit of the warlord during turbulent times in the kingdom. Written by Keith Loh",
                            DirectorID = 10,
                            DirectorName = "Akira Kurosawa ",
                            GenreID = 5,
                            GenreName = "Drama",
                            IMBDScore = 8.0,
                            Language = "Japanese",
                            PhotoURL = "Kagemusha_poster.jpg",
                            Price = 4.9900000000000002,
                            SoldItems = 0,
                            Title = "Kagemusha",
                            UserId = 0,
                            YearOfRelease = new DateTime(1980, 10, 10, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Country = "USA",
                            Description = "Maximus is a powerful Roman general, loved by the people and the aging Emperor, Marcus Aurelius. Before his death,the Emperor chooses Maximus to be his heir over his own son, Commodus, and a power struggle leaves Maximus and his family condemned to death.The powerful general is unable to save his family, and his loss of will allows him to get captured and put into the Gladiator games until he dies.The only desire that fuels him now is the chance to rise to the top so that he will be able to look into the eyes of the man who will feel his revenge.Written by Chris Terry",
                            DirectorID = 9,
                            DirectorName = "Ridley Scott",
                            GenreID = 4,
                            GenreName = "Adventure",
                            IMBDScore = 8.5,
                            Language = "English",
                            PhotoURL = "Gladiator_(2000_film_poster).png",
                            Price = 9.9900000000000002,
                            SoldItems = 0,
                            Title = "Gladiator",
                            UserId = 0,
                            YearOfRelease = new DateTime(2000, 5, 5, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Country = "USA",
                            Description = "After a gentle alien becomes stranded on Earth, the being is discovered and befriended by a young boy named Elliott.Bringing the extraterrestrial into his suburban California house, Elliott introduces E.T., as the alien is dubbed, to his brother and his little sister, Gertie,and the children decide to keep its existence a secret. Soon, however, E.T. falls ill, resulting in government intervention and a dire situation for both Elliott and the alien.Written by Jwelch5742",
                            DirectorID = 1,
                            DirectorName = "Steven Spielberg",
                            GenreID = 6,
                            GenreName = "Fantasy",
                            IMBDScore = 7.7999999999999998,
                            Language = "English",
                            PhotoURL = "V1.jpg",
                            Price = 11.99,
                            SoldItems = 0,
                            Title = "E.T. the Extra-Terrestria",
                            UserId = 0,
                            YearOfRelease = new DateTime(1982, 6, 11, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Country = "USA",
                            Description = "It's a hot summer on Amity Island, a small community whose main business is its beaches. When new Sheriff Martin Brody discovers the remains of a shark attackvictim, his first inclination is to close the beaches to swimmers. This doesn't sit well with Mayor Larry Vaughn and several of the local businessmen.Brody backs down to his regret as that weekend a young boy is killed by the predator. The dead boy's mother puts out a bounty on the shark and Amity is soon swamped withamateur hunters and fisherman hoping to cash in on the reward. A local fisherman with much experience hunting sharks, Quint, offers to hunt down the creature for a hefty fee.Soon Quint, Brody and Matt Hooper from the Oceanographic Institute are at sea hunting the Great White shark. As Brody succinctly surmises after their first encounter with thecreature, they're going to need a bigger boat. Written by garykmcd",
                            DirectorID = 1,
                            DirectorName = "Steven Spielberg",
                            GenreID = 9,
                            GenreName = "Adventure",
                            IMBDScore = 8.4000000000000004,
                            Language = "English",
                            PhotoURL = "AL_.jpg",
                            Price = 7.9900000000000002,
                            SoldItems = 0,
                            Title = "Jaws",
                            UserId = 0,
                            YearOfRelease = new DateTime(1975, 6, 20, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Country = "USA",
                            Description = "Two parallel stories are told. In the first, a group of research scientists from a variety of backgrounds are investigating the strange appearance of items inremote locations, primarily desert regions. In continuing their investigation, one of the lead scientists, a Frenchman named Claude Lacombe,incorporates the Kodály method of music education as a means of communication in their work. The response, in turn, at first baffles the researchers,until American cartographer David Laughlin deciphers the meaning of the response. In the second, electric company lineman and family man Roy Neary and single motherJillian Guiler are among some individuals in Muncie, Indiana who experience some paranormal activity before some flashes of bright lights in the sky, which theybelieve to be a UFO. Roy becomes obsessed with what he saw, unlike some others, especially in some form of authority, who refuse to acknowledge their belief thatit was a UFO in not wanting to appear crazy.",
                            DirectorID = 1,
                            DirectorName = "Steven Spielberg",
                            GenreID = 10,
                            GenreName = "Sci-fi",
                            IMBDScore = 7.5999999999999996,
                            Language = "English",
                            PhotoURL = "99.jpg",
                            Price = 13.99,
                            SoldItems = 0,
                            Title = "Close Encounters of the Third Kind",
                            UserId = 0,
                            YearOfRelease = new DateTime(1977, 11, 14, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domashna.Data.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Domashna.Data.Entities.RentingMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RentingMovies");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "b4280b6a-0613-4cbd-a9e6-f1701e926e73",
                            ConcurrencyStamp = "3b3a676a-e333-4e2b-a3f6-2dfab788ac81",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b4280b6a-0613-4cbd-a9e6-f1701e926e74",
                            ConcurrencyStamp = "4a8b4a38-559b-4afe-a406-167773e3c3bf",
                            Name = "editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "b4280b6a-0613-4cbd-a9e6-f1701e926e75",
                            ConcurrencyStamp = "c2ff1e45-dfe2-4ff4-b56c-34f62d35e079",
                            Name = "guest",
                            NormalizedName = "GUEST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "b4280b6a-0613-4cbd-a9e6-f1701e926e73",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8554266-b401-4519-9aeb-a9283053fc58",
                            Email = "admin@onlinemoviestore.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ONLINEMOVIESTORE.COM",
                            NormalizedUserName = "ADMIN@ONLINEMOVIESTORE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJZ67j2KyZEUwQX+E64YQC8w8SuvwnhGJ8nQiZSoBrUtRuWWKyHgOSkEFzuiJ/EWVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin@onlinemoviestore.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "b4280b6a-0613-4cbd-a9e6-f1701e926e73",
                            RoleId = "b4280b6a-0613-4cbd-a9e6-f1701e926e73"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domashna.Data.Entities.Movie", b =>
                {
                    b.HasOne("Domashna.Data.Entities.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domashna.Data.Entities.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domashna.Data.Entities.Photo", b =>
                {
                    b.HasOne("Domashna.Data.Entities.Movie", null)
                        .WithMany("Photos")
                        .HasForeignKey("MovieId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
